In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]
meu_array = np.array(lista)
meu_array

array([1, 2, 3, 4, 5, 6])

In [3]:
lista = [1, 2, 3, 4, 5, 6]
meu_array = np.array(lista, dtype=float)
meu_array

array([1., 2., 3., 4., 5., 6.])

In [4]:
lista_de_listas = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
meu_array = np.array(lista_de_listas)
meu_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.empty(4) # Guarda na memória de forma temporárias os valores para serem usados posteriormente.

array([0., 0., 0., 0.])

In [11]:
np.linspace(0, 10, 5) # 5 números igualmente espaçados entre 0 e 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.full(5, 6) # Imprime 5 valores de 6

array([6, 6, 6, 6, 6])

INFORMAÇÕES DO ARRAY

In [17]:
lista = [1, 2, 3, 4, 5, 6]
array1 = np.array(lista, dtype=float)
lista_de_listas = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2 = np.array(lista_de_listas)

In [19]:
array1

array([1., 2., 3., 4., 5., 6.])

In [21]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array1.ndim # Verifica o número de dimensões de um vetor

1

In [25]:
array2.ndim

2

In [27]:
array1.size # Verifica o número de elementos de um vetor

6

In [29]:
array2.size

9

In [31]:
array1.shape # Verifica o número de linhas e colunas

(6,)

In [33]:
array2.shape

(3, 3)

INDEXAÇÃO E FATIAMENTO

In [37]:
lista = [1, 2 ,3, 4, 5, 6]
array1 = np.array(lista, dtype=float)

array1

array([1., 2., 3., 4., 5., 6.])

In [40]:
array1[0]

1.0

In [42]:
array1[:4]

array([1., 2., 3., 4.])

In [47]:
array1[[1, 3]] # Pega elemtnso solto em um array

array([2., 4.])

In [51]:
array1[array1 < 5]

array([1., 2., 3., 4.])

In [56]:
array1[[True, False, False, False, True, True]]

array([1., 5., 6.])

In [59]:
np.nonzero(array1 % 2 == 0) # Pega os índices dos números divisíveis por 2

(array([1, 3, 5], dtype=int64),)

OPERAÇÕES BÁSICAS

In [80]:
lista1 = [0, 4, 5, 6, 9]
lista2 = [9, 3, 4, 5, 6]
lista_soma = []
for c, d in zip(lista1, lista2):
    lista_soma.append(c + d)
lista_soma

[9, 7, 9, 11, 15]

In [84]:
array1 = np.array(lista1)
array2 = np.array(lista2)

soma = array1 +array2
soma


array([ 9,  7,  9, 11, 15])

In [86]:
sub = array1 - array2
sub

array([-9,  1,  1,  1,  3])

In [90]:
div = array1/array2
div

array([0.        , 1.33333333, 1.25      , 1.2       , 1.5       ])

In [92]:
mult = array1*array2
mult

array([ 0, 12, 20, 30, 54])

In [96]:
array3 = np.full(5, 5)
array3

array([5, 5, 5, 5, 5])

In [98]:
array1 + array3

array([ 5,  9, 10, 11, 14])

FUNÇÕES ÚTEIS

In [100]:
array1 = np.array([0, 1, 2, 3, 4, 5])

In [103]:
array1.sum()

15

In [105]:
array1.mean()

2.5

In [107]:
array1.max()

5

In [111]:
array1.min()

0

In [113]:
array1.argmax() # Retorna o índice do máximno

5

In [115]:
array1.argmin()

0

In [117]:
array1.cumsum() # Função para somar todos os elementos um por um

array([ 0,  1,  3,  6, 10, 15], dtype=int32)

COMPARANDO ARRAY COM LISTA

In [119]:
import random

In [157]:
minha_lista = [random.randint(0, 100) for i in range(10)] # LISTA
meu_array = np.random.randint(0, 100, 10)             # ARRAY

In [158]:
minha_lista

[63, 77, 86, 69, 66, 84, 99, 21, 33, 13]

In [159]:
meu_array

array([74, 76, 83, 97, 19, 63, 98, 49, 47, 37])

In [160]:
soma = 0    # FAZENDO COM LISTA
for el in minha_lista:
    soma = soma + el
soma

611

In [161]:
sum(minha_lista)    # FAZENDO COMO LISTA

611

In [163]:
meu_array.sum()     # FAZENDO COM NUMPY

643